.\"
.\" repology - Command line interface to Repology.org
.\"
.\" Copyright (c) 2024-2025 Brian Callahan <bcallah@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd January 5, 2025
.Dt REPOLOGY 1
.Os
.Sh NAME
.Nm repology
.Nd command line interface to Repology.org
.Sh SYNOPSIS
.Nm
.Op options
.Op Ar package ...
.Sh DESCRIPTION
.Nm
is a utility that retrieves package information from Repology.org.
.Pp
By default,
.Nm
selects an appropriate repository based on your operating system:
.Pp
.Dl Alpine Ar alpine_edge
.Dl Debian Ar debian_unstable
.Dl Fedora Ar fedora_rawhide
.Dl FreeBSD Ar freebsd
.Dl macOS Ar homebrew
.Dl NetBSD Ar pkgsrc_current
.Dl OpenBSD Ar openbsd
.Dl OpenIndiana Ar openindiana
.Dl Ubuntu Ar ubuntu_ Ns Ar <releaseYear>_<releaseMonth>
.Dl Windows Ar chocolatey
.Pp
All other users will need to specify their repository with the
.Fl -repo
flag.
.Pp
.Nm
returns information in the following format:
.Pp
.Dl Port category/port name
.Dl Package version
.Dl Latest version
.Dl Maintainer email address
.Pp
Output is sorted by port category,
then port name.
.Pp
As per the API documentation,
.Nm
returns up to 200 items in a single API call.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl -repo Ar REPO
Override repository selection with
.Ar REPO .
.It Fl -begin Ar PROJECT
Get up to 200 projects starting with
.Ar PROJECT .
.It Fl -end Ar PROJECT
Get up to 200 projects ending with
.Ar PROJECT .
.It Fl -search Ar NAME
Project name substring to look for.
.It Fl -maintainer Ar EMAIL
Return projects maintained by specified
.Ar EMAIL .
.It Fl -category Ar NAME
Return projects in specified category.
.It Fl -inrepo Ar REPO
Return projects present in specified
.Ar REPO .
If this option is not issued,
.Ar REPO
will be set to the value of
.Fl -repo
or the auto-detected repository if the
.Fl -repo
option is also not issued.
.It Fl -notinrepo Ar REPO
Return projects absent in specified
.Ar REPO .
.It Fl -repos Ar NUMBER
Return projects present in specified
.Ar NUMBER
of repositories.
For all options that take a
.Ar NUMBER
argument,
exact values and open/closed ranges are allowed,
.Em e.g. ,
1, 5-, -3, 2-7.
.It Fl -families Ar NUMBER
Return projects present in specified
.Ar NUMBER
of repository families.
.It Fl -repos_newest Ar NUMBER
Return projects which are up to date in the specified
.Ar NUMBER
of repositories.
.It Fl -families_newest Ar NUMBER
Return projects which are up to date in the specified
.Ar NUMBER
of repository families.
.It Fl -newest
Return only packages marked newest.
.It Fl -outdated
Return only packages marked outdated.
.It Fl -problematic
Return only packages marked problematic.
.It Fl -sort_package
Sort output by package name instead of port category/port name.
Prepend output with package name.
.It Fl -all
Display package information for all known repositories in the following format:
.Pp
.Dl Repository
.Dl Package name
.Dl Package version
.Dl Latest version
.It Fl -version
Print version information and exit.
.It Fl -help
Print help information and exit.
.El
.Pp
Package version is colored based on its status.
The colors are as follows:
.Bl -tag -width Ds
.It Green
The package is up to date.
.It Red
The package is outdated.
.It Cyan
The package is either a development version, unique to this repo,
or a rolling release.
.It Yellow
The package is a legacy version.
.It Magenta
The package has no known versioning scheme.
.It Blue
The package version is incorrect, untrusted, or otherwise ignored.
.El
.Sh EXIT STATUS
The
.Nm
utility exits 0 on success, and >0 if an error occurs.
.Sh EXAMPLES
Get information on the Digital Mars D compiler from the auto-detected
repository:
.Pp
.Dl repology dmd
.Pp
Get information on the Digital Mars D compiler from all repositories:
.Pp
.Dl repology --all dmd
.Pp
Get 200 items from pkgsrc:
.Pp
.Dl repology --repo pkgsrc
.Pp
Get information about both Chrome and Firefox from
.Fx
ports:
.Pp
.Dl repology --repo freebsd chromium firefox
.Pp
Get up to 200 packages maintained by ports@openbsd.org,
starting with coreutils:
.Pp
.Dl repology --maintainer ports@openbsd.org --begin coreutils
.Sh SEE ALSO
The repology API documentation can be found at
.Lk https://repology.org/api/v1 .
.Sh AUTHORS
.Nm
was written by
.An Brian Callahan Aq Mt bcallah@openbsd.org .
.Sh CAVEATS
Not all repositories may contain all information.
